# Generated by Django 5.2.6 on 2025-10-25 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('api', 'API'), ('scraper', 'Web Scraper'), ('manual', 'Manual Entry')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('update_frequency', models.PositiveIntegerField(default=60)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('title_selector', models.CharField(blank=True, max_length=200, null=True)),
                ('content_selector', models.CharField(blank=True, max_length=200, null=True)),
                ('image_selector', models.CharField(blank=True, max_length=200, null=True)),
                ('date_selector', models.CharField(blank=True, max_length=200, null=True)),
                ('total_scraped', models.PositiveIntegerField(default=0)),
                ('successful_scrapes', models.PositiveIntegerField(default=0)),
                ('failed_scrapes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
                'db_table': 'news_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('articles_found', models.PositiveIntegerField(default=0)),
                ('articles_scraped', models.PositiveIntegerField(default=0)),
                ('articles_processed', models.PositiveIntegerField(default=0)),
                ('max_articles', models.PositiveIntegerField(default=100)),
                ('force_update', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='scraper.newssource')),
            ],
            options={
                'verbose_name': 'Scraping Job',
                'verbose_name_plural': 'Scraping Jobs',
                'db_table': 'scraping_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scraper.scrapingjob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_logs', to='scraper.newssource')),
            ],
            options={
                'verbose_name': 'Scraping Log',
                'verbose_name_plural': 'Scraping Logs',
                'db_table': 'scraping_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField()),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('published', 'Published')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('title_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('quality_score', models.FloatField(default=0.0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_articles', to='scraper.newssource')),
            ],
            options={
                'verbose_name': 'Scraped Article',
                'verbose_name_plural': 'Scraped Articles',
                'db_table': 'scraped_articles',
                'ordering': ['-scraped_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
