# Generated by Django 5.2.6 on 2025-10-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_video'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Default category for scraped content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_sources', to='content.category'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='icon',
            field=models.ImageField(blank=True, help_text='Source icon/logo', null=True, upload_to='sources/icons/'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Icon/logo URL for the source', null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Default tags for scraped content', related_name='news_sources', to='content.tag'),
        ),
        migrations.AddField(
            model_name='scrapedarticle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category inherited from source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_articles', to='content.category'),
        ),
        migrations.AddField(
            model_name='scrapedarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags inherited from source', related_name='scraped_articles', to='content.tag'),
        ),
    ]
