# Generated by Django 5.2.6 on 2025-10-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='content.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='primary_category_archived_at',
            field=models.DateTimeField(blank=True, help_text='When article was archived from primary category', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='primary_category_expires_at',
            field=models.DateTimeField(blank=True, help_text='When to auto-archive from primary category', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='secondary_articles', to='content.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_categories_archived_at',
            field=models.DateTimeField(blank=True, help_text='When article was archived from secondary categories', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_categories_expire_at',
            field=models.DateTimeField(blank=True, help_text='When to auto-archive from secondary categories', null=True),
        ),
    ]
