# Generated by Django 5.2.6 on 2025-10-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_article_category_article_primary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='URL for featured image (alternative to file upload)', null=True),
        ),
    ]
