# Generated by Django 5.2.6 on 2025-10-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_featured_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived_secondary_categories',
            field=models.ManyToManyField(blank=True, help_text='Secondary categories this article has been archived from', related_name='archived_secondary_articles', to='content.category'),
        ),
    ]
