# Generated by Django 5.2.7 on 2025-11-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
