# Generated by Django 4.2.7 on 2025-11-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_opinion_note',
            field=models.TextField(blank=True, help_text="Opinion disclaimer note (e.g., 'This article is the sole opinion of the above author and in no way Somali Report's point of view')", null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='manual_author_affiliation',
            field=models.CharField(blank=True, help_text="Author's affiliation/organization", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='manual_author_name',
            field=models.CharField(blank=True, help_text='Manually entered author name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='show_manual_author',
            field=models.BooleanField(default=False, help_text='If True, display manual author info instead of the automatic author'),
        ),
        migrations.AddField(
            model_name='article',
            name='show_opinion_note',
            field=models.BooleanField(default=False, help_text='If True, display the opinion note with the article'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
