# Generated by Django 4.2.7 on 2025-12-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_add_manual_author_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='manual_author_image',
            field=models.ImageField(blank=True, help_text='Manual author profile picture', null=True, upload_to='authors/'),
        ),
    ]
