# Generated by Django 4.2.7 on 2025-12-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_article_manual_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='manual_author_image_url',
            field=models.URLField(blank=True, help_text='URL for manual author profile picture (alternative to file upload)', null=True),
        ),
    ]
