# Generated by Django 5.2.7 on 2025-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_article_author_opinion_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="manual_author_image",
            field=models.ImageField(
                blank=True,
                help_text="Manual author profile picture",
                null=True,
                upload_to="authors/",
            ),
        ),
    ]
