# Generated by Django 4.2.7 on 2025-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_article_manual_author_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='external_video_url',
            field=models.URLField(blank=True, help_text='External video URL (e.g. YouTube)', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
