# Generated by Django 5.2.7 on 2025-12-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_article_manual_author_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="manual_author_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL for manual author profile picture (alternative to file upload)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="external_video_url",
            field=models.URLField(
                blank=True, help_text="External video URL (e.g. YouTube)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
