# Generated by Django 5.2.15 on 2026-06-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_video_external_video_url_alter_video_video_file"),
        ("content", "0011_articlesave"),
    ]

    operations = []
